name: "Share With Friends - Frontend"
description: "Share your holidays expenses"
version: "1.0.0"
slug: "share_friends"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ingress: true
ingress_port: 4200
ports:
  80/tcp: null
  4200/tcp: 4200
environment:
  BACKEND_URL: production